### ISSUE TITLE
Error on Vercel

### ISSUE THREAD

**Issue by hgsaldanhadev** [Julien-Marcou/Unicode-Emoji#1]
I'm receiving this error using this package on Vercel (Node 14):

```
ERROR	Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /var/task/node_modules/unicode-emoji/index.js
require() of ES modules is not supported.
```

**Comment by Julien-Marcou** [comment]
Sorry for the delay, I missed the notification for this issue 😣

This package is using the new `import` syntax from ES6, you cannot use it with `require`.

The new `import` syntax is fully supported by Node.js since the v14, so you should not have any problem to do it.

**Comment by Julien-Marcou** [comment]
A solution to your problem if your project is using CommonJS instead of ES Module, would be to use dynamic import (as static import is only supported inside ES Modules for Node.js) :

```javascript
const unicodeEmoji = await import('unicode-emoji');
```

Also, you'll need to import it inside an async function, as top-level await is not supported for CommonJS.
